package com.aait.ezakbus.models.line_branch_model

data class Data(
    val arrive_date_time: String?,
    val available_car_persons: Int?,
    val avatar: String?,
    val car_brand: String?,
    val car_image: String?,
    val car_number: String?,
    val car_type_id: Int?,
    val currency: String?,
    val current_lat: String?,
    val current_long: String?,
    val current_order_persons: Int?,
    val datetime: String?,
    val direction: String?,
    val distance: String?,
    val end_address: String?,
    val end_lat: String?,
    val end_long: String?,
    val end_point: String?,
    val expected_period: String?,
    val id: Int?,
    val max_car_persons: Int?,
    val expected_time:String?="",
    val name: String?,
    val phone: String?,
    val rate: Int?,
    val start_address: String?,
    val start_lat: String?,
    val start_long: String?,
    val start_point: String?,
    val traffic_line: String?,
    val traffic_line_id: Int?,
    val traffic_line_price: String?,
    val type: String?
)